export const jobs = [
  {
    id: 1,
    title: "Senior Software Engineer",
    location: "Rajbagh, Srinagar",
    region: "Srinagar, Jammu & Kashmir",
    country: "India",
    company: "Raybit Technologies",
    tags: ["Java", "Python", "AWS", "Node.js"],
    description: `Raybit Technologies is shaping the digital landscape with cutting-edge technology solutions. We value creativity, initiative, and the passion to build impactful products.`,
    role: `As a Senior Software Engineer, you will design, develop, test, and deploy robust software systems. You will mentor junior engineers and collaborate closely with product and design teams to deliver scalable solutions.`,
    skills: [
      "Expertise in Java, Python, or JavaScript.",
      "Solid understanding of system design and software architecture.",
      "Experience with REST APIs, databases (SQL/NoSQL), and cloud platforms (AWS/Azure).",
      "Knowledge of version control (Git) and CI/CD pipelines.",
      "Strong debugging and optimization skills.",
    ],
    attributes: [
      "Proactive and self-driven.",
      "Strong communication and mentoring abilities.",
      "Ability to adapt quickly to new tools and frameworks.",
    ],
  },
  {
    id: 2,
    title: "Back End Developer",
    location: "Rajbagh, Srinagar",
    region: "Srinagar, Jammu & Kashmir",
    country: "India",
    company: "Raybit Technologies",
    tags: ["Node.js", "Python", "Databases", "Microservices"],
    description: `Join Raybit Technologies as a Back End Developer and help build secure, high-performance services that power our products.`,
    role: `Design and implement APIs, manage database systems, and develop server-side logic. Optimize performance, ensure scalability, and work alongside front-end teams.`,
    skills: [
      "Strong proficiency in Node.js or Python.",
      "Experience designing RESTful and GraphQL APIs.",
      "Database expertise: MongoDB, PostgreSQL, or MySQL.",
      "Understanding of containerization (Docker, Kubernetes).",
    ],
    attributes: [
      "Analytical mindset and problem-solving skills.",
      "Team player with clear communication.",
      "Focus on security and performance best practices.",
    ],
  },
  {
    id: 3,
    title: "Front End Developer",
    location: "Rajbagh, Srinagar",
    region: "Srinagar, Jammu & Kashmir",
    country: "India",
    company: "Raybit Technologies",
    tags: ["React", "Next.js", "JavaScript", "UI/UX"],
    description: `Raybit Technologies seeks a Front End Developer to build intuitive, responsive interfaces and deliver great user experiences.`,
    role: `Develop and maintain web applications using React and Next.js. Collaborate with design teams to turn mockups into functional components.`,
    skills: [
      "Strong skills in HTML, CSS, JavaScript, and modern frameworks (React, Next.js).",
      "Experience with responsive and cross-browser design.",
      "Knowledge of state management tools (Redux, Context API).",
      "Basic understanding of SEO and accessibility best practices.",
    ],
    attributes: [
      "Attention to detail and eye for design.",
      "Collaborative mindset.",
      "Ability to learn new frameworks and tools quickly.",
    ],
  },
  {
    id: 4,
    title: "Mobile App Developer",
    location: "Rajbagh, Srinagar",
    region: "Srinagar, Jammu & Kashmir",
    country: "India",
    company: "Raybit Technologies",
    tags: ["React Native", "Flutter", "Android", "iOS"],
    description: `Raybit Technologies is expanding its mobile team! Develop high-quality cross-platform mobile applications.`,
    role: `Design, develop, and maintain mobile apps with React Native or Flutter. Work closely with backend teams and designers to deliver smooth experiences.`,
    skills: [
      "Strong grasp of React Native or Flutter.",
      "Experience publishing apps to App Store/Google Play.",
      "Familiarity with REST APIs and integration.",
      "Understanding of mobile performance optimization.",
    ],
    attributes: [
      "Problem-solver with a product mindset.",
      "Good communication and teamwork.",
      "Focus on usability and performance.",
    ],
  },
  {
    id: 5,
    title: "Project Manager",
    location: "Rajbagh, Srinagar",
    region: "Srinagar, Jammu & Kashmir",
    country: "India",
    company: "Raybit Technologies",
    tags: ["Agile", "Scrum", "Leadership", "Planning"],
    description: `Raybit Technologies is looking for an experienced Project Manager to lead cross-functional teams and deliver projects on time.`,
    role: `Plan and oversee projects from conception to completion. Coordinate teams, manage timelines, and ensure deliverables meet quality standards.`,
    skills: [
      "Proven experience managing software projects.",
      "Familiarity with Agile/Scrum methodologies.",
      "Excellent organizational and leadership skills.",
      "Strong written and verbal communication.",
    ],
    attributes: [
      "Proactive and detail-oriented.",
      "Ability to motivate teams and resolve conflicts.",
      "Adaptable to dynamic project needs.",
    ],
  },
  {
    id: 6,
    title: "UI/UX Designer",
    location: "Rajbagh, Srinagar",
    region: "Srinagar, Jammu & Kashmir",
    country: "India",
    company: "Raybit Technologies",
    tags: ["Figma", "Wireframes", "Prototyping", "User Research"],
    description: `Join our design team to craft delightful user experiences and interfaces that align with Raybit’s vision.`,
    role: `Collaborate with stakeholders to understand requirements, conduct user research, design wireframes and prototypes, and work with developers for pixel-perfect execution.`,
    skills: [
      "Proficiency in Figma or Adobe XD.",
      "Strong portfolio showcasing UI/UX projects.",
      "Experience with user research and usability testing.",
      "Ability to translate ideas into elegant interfaces.",
    ],
    attributes: [
      "Creative and user-focused approach.",
      "Strong communication and presentation skills.",
      "Collaborative and open to feedback.",
    ],
  },
];
