export const jobs = [
  {
    id: 1,
    title: "Junior Software Engineer",
    location: " Rajbagh, Srinagar",
    region: " Srinagar, Jammu & Kashmir",
    country: "India",
    company: "Raybit Technologies",
    tags: ["Python", "AWS", "Nodejs"],
    description: `Today, the digital landscape is rapidly evolving and full of potential. At Raybit Technologies, we believe that innovation thrives when creativity and fresh ideas are encouraged. We are committed to fostering an environment that allows innovation to flourish, because your first step deserves the right foundation.`,
    role: `As a Senior Software Engineer, you will contribute to the design, development, testing, and deployment of cutting-edge solutions. Collaborate with cross-functional teams, mentor junior engineers, and ensure best practices are followed.`,
    skills: [
      "Strong understanding of software engineering principles and programming languages.",
      "Proficiency in languages like Java, Python, or JavaScript.",
      "Knowledge of frameworks, RESTful APIs, databases (SQL/NoSQL), and software architecture.",
      "Ability to translate business requirements and convert them to technical designs.",
      "Experience with version control systems (Git) and CI/CD pipelines.",
    ],
    attributes: [
      "Excellent analytical and problem-solving skills.",
      "Strong communication skills and teamwork.",
      "Adaptability to learn new technologies quickly.",
    ],
  },
  {
    id: 2,
    title: "Back End Developer",
    location: "Srinagar",
    region: "Switzerland",
    country: "Switzerland",
    company: "Raybit Technologies",
    tags: ["Python", "AWS", "Technology"],
    description: `Similar job description...`,
    role: `Similar role description...`,
    skills: ["Same skills..."],
    attributes: ["Same attributes..."],
  },
  {
    id: 3,
    title: "Front End Developer",
    location: "Srinagar",
    region: "Switzerland",
    country: "Switzerland",
    company: "Raybit Technologies",
    tags: ["Python", "AWS", "Technology"],
    description: `Similar job description...`,
    role: `Similar role description...`,
    skills: ["Same skills..."],
    attributes: ["Same attributes..."],
  },
  {
    id: 4,
    title: "Mobile App Developer",
    location: "Srinagar",
    region: "Switzerland",
    country: "Switzerland",
    company: "Raybit Technologies",
    tags: ["Python", "AWS", "Technology"],
    description: `Similar job description...`,
    role: `Similar role description...`,
    skills: ["Same skills..."],
    attributes: ["Same attributes..."],
  },
  {
    id: 5,
    title: "Project Manager",
    location: "Srinagar",
    region: "Switzerland",
    country: "Switzerland",
    company: "Raybit Technologies",
    tags: ["Python", "AWS", "Technology"],
    description: `Similar job description...`,
    role: `Similar role description...`,
    skills: ["Same skills..."],
    attributes: ["Same attributes..."],
  },
  {
    id: 6,
    title: "UI/UX",
    location: "Srinagar",
    region: "Switzerland",
    country: "Switzerland",
    company: "Raybit Technologies",
    tags: ["Python", "AWS", "Technology"],
    description: `Similar job description...`,
    role: `Similar role description...`,
    skills: ["Same skills..."],
    attributes: ["Same attributes..."],
  },
];
