export const jobs = [
  {
    id: 1,
    title: "Software Development Intern",
    location: "Rajbagh, Srinagar",
    region: "Srinagar, Jammu & Kashmir",
    country: "India",
    company: "Raybit Technologies",
    tags: ["JavaScript", "React", "Node.js"],
    description: `At Raybit Technologies, our interns get real-world experience by contributing to meaningful projects under expert guidance.`,
    role: `As a Software Development Intern, you’ll work on full-stack projects, learn modern frameworks, and gain hands-on coding experience.`,
    skills: [
      "Basic understanding of programming languages like JavaScript, Python.",
      "Familiarity with web development concepts (HTML, CSS, React).",
      "Good problem-solving skills and willingness to learn.",
    ],
    attributes: [
      "Curiosity and eagerness to learn.",
      "Team player with strong communication skills.",
      "Ability to adapt to a fast-paced environment.",
    ],
  },
  {
    id: 2,
    title: "Data Analyst Intern",
    location: "Srinagar",
    region: "Jammu & Kashmir",
    country: "India",
    company: "Raybit Technologies",
    tags: ["Python", "SQL", "Excel"],
    description: `Gain practical experience in data analytics by working with real datasets and modern tools.`,
    role: `Assist in collecting, cleaning, and analyzing data to support decision-making.`,
    skills: [
      "Basic understanding of data analysis techniques.",
      "Familiarity with Python or R for data manipulation.",
      "Knowledge of Excel and basic SQL queries.",
    ],
    attributes: [
      "Strong attention to detail.",
      "Analytical mindset.",
      "Good communication skills.",
    ],
  },
  {
    id: 3,
    title: "Marketing Intern",
    location: "Srinagar",
    region: "Jammu & Kashmir",
    country: "India",
    company: "Raybit Technologies",
    tags: ["Digital Marketing", "Social Media", "Content Creation"],
    description: `Join our marketing team and learn how to create impactful campaigns.`,
    role: `Support social media management, content creation, and campaign analytics.`,
    skills: [
      "Basic understanding of digital marketing.",
      "Familiarity with social media platforms.",
      "Creative thinking and writing skills.",
    ],
    attributes: [
      "Strong communication skills.",
      "Creativity and initiative.",
      "Ability to work collaboratively.",
    ],
  },
  {
    id: 4,
    title: "UI/UX Design Intern",
    location: "Srinagar",
    region: "Jammu & Kashmir",
    country: "India",
    company: "Raybit Technologies",
    tags: ["Figma", "Adobe XD", "User Research"],
    description: `Learn how to design user-friendly interfaces and improve user experiences.`,
    role: `Assist in creating wireframes, prototypes, and conducting user research.`,
    skills: [
      "Basic understanding of design tools like Figma or Adobe XD.",
      "Knowledge of design principles and user-centered design.",
      "Good visual and creative skills.",
    ],
    attributes: [
      "Attention to detail.",
      "Creative mindset.",
      "Ability to accept feedback and iterate designs.",
    ],
  },
  {
    id: 5,
    title: "HR Intern",
    location: "Srinagar",
    region: "Jammu & Kashmir",
    country: "India",
    company: "Raybit Technologies",
    tags: ["HR", "Recruitment", "Communication"],
    description: `Support our HR team in recruitment and employee engagement initiatives.`,
    role: `Assist in screening resumes, coordinating interviews, and maintaining HR databases.`,
    skills: [
      "Basic understanding of HR processes.",
      "Good organizational skills.",
      "Strong communication and interpersonal skills.",
    ],
    attributes: [
      "Professional and approachable demeanor.",
      "Attention to confidentiality.",
      "Team player.",
    ],
  },
  {
    id: 6,
    title: "Business Development Intern",
    location: "Srinagar",
    region: "Jammu & Kashmir",
    country: "India",
    company: "Raybit Technologies",
    tags: ["Sales", "Communication", "Market Research"],
    description: `Learn how to identify new business opportunities and build client relationships.`,
    role: `Assist in market research, outreach, and proposal preparation.`,
    skills: [
      "Basic understanding of sales and business development.",
      "Good communication and negotiation skills.",
      "Ability to research and analyze markets.",
    ],
    attributes: [
      "Result-oriented attitude.",
      "Proactive and self-motivated.",
      "Good presentation skills.",
    ],
  },
];
