import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ExitIntentPopup from "./components/ExitIntentPopup";
import AnnouncementBanner from "./components/AnnouncementBanner";
import Script from "next/script";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata = {
  title: "Raybit Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} hide-scrollbar`}>
      <body className="hide-scrollbar bg-[#FBFCFE]">
        <AnnouncementBanner />
        <Navbar />
        <ExitIntentPopup />
        <main>{children}</main>
        <Footer />
        {/* ✅ Tawk.to Script using Next.js Script component */}
        <Script
          id="tawkto-script"
          strategy="afterInteractive" // Loads script after page is interactive
          dangerouslySetInnerHTML={{
            __html: `
              var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
              (function(){
                var s1=document.createElement("script"),
                    s0=document.getElementsByTagName("script")[0];
                s1.async=true;
                s1.src='https://embed.tawk.to/65aa9ac48d261e1b5f55818d/1hkh6p500';
                s1.charset='UTF-8';
                s1.setAttribute('crossorigin','*');
                s0.parentNode.insertBefore(s1,s0);
              })();
            `,
          }}
        />
      </body>
    </html>
  );
}
